server:
  port: 8776
spring:
  application:
    name: eurekaclient
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    locator:
      discovery:
        enabled: true
  sleuth:
      sampler:
          percentage: 1.0
